version: "3.9"
services:
  realsense_ros:
    extends:
      file: docker-compose-gui.yml
      service: realsense_ros
    environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
